### PR TITLE
Replace doctrine/doctrine-cache-bundle by symfony/cache

### PR DESCRIPTION
**Pull request by Lctrs**
Following changes made in https://github.com/symfony/recipes-contrib/pull/697

### CODE REVIEW

**Comment by dbu** [comment]
thanks, agree that we should do this.

looks like there are too many options for composer in the lowest version build. that is always tricky... @ElectricMaxxx any ideas?

**Comment by Lctrs** [comment]
@dbu Should be good :)

**Review by dbu — APPROVED** [review]
that lowest version build :scream: `symfony/templating (v2.1.0): Loading from cache` :joy: 

thanks for the cleanup of the build. i will probably use that flex setup instruction in other places too.

**Comment by Lctrs** [comment]
To be fair, I [didn't gone very far away](https://github.com/doctrine/DoctrineBundle/blob/f4262c83196cc633af991cddc061f54f080bf1a6/.travis.yml) :smile:

**Pull request merged**
